// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/diseas.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DiseasService_DiseasGet_FullMethodName = "/services.v1.DiseasService/DiseasGet"
)

// DiseasServiceClient is the client API for DiseasService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiseasServiceClient interface {
	DiseasGet(ctx context.Context, in *DiseasGetRequest, opts ...grpc.CallOption) (*DiseasGetReply, error)
}

type diseasServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiseasServiceClient(cc grpc.ClientConnInterface) DiseasServiceClient {
	return &diseasServiceClient{cc}
}

func (c *diseasServiceClient) DiseasGet(ctx context.Context, in *DiseasGetRequest, opts ...grpc.CallOption) (*DiseasGetReply, error) {
	out := new(DiseasGetReply)
	err := c.cc.Invoke(ctx, DiseasService_DiseasGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiseasServiceServer is the server API for DiseasService service.
// All implementations should embed UnimplementedDiseasServiceServer
// for forward compatibility
type DiseasServiceServer interface {
	DiseasGet(context.Context, *DiseasGetRequest) (*DiseasGetReply, error)
}

// UnimplementedDiseasServiceServer should be embedded to have forward compatible implementations.
type UnimplementedDiseasServiceServer struct {
}

func (UnimplementedDiseasServiceServer) DiseasGet(context.Context, *DiseasGetRequest) (*DiseasGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiseasGet not implemented")
}

// UnsafeDiseasServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiseasServiceServer will
// result in compilation errors.
type UnsafeDiseasServiceServer interface {
	mustEmbedUnimplementedDiseasServiceServer()
}

func RegisterDiseasServiceServer(s grpc.ServiceRegistrar, srv DiseasServiceServer) {
	s.RegisterService(&DiseasService_ServiceDesc, srv)
}

func _DiseasService_DiseasGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiseasGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiseasServiceServer).DiseasGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiseasService_DiseasGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiseasServiceServer).DiseasGet(ctx, req.(*DiseasGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiseasService_ServiceDesc is the grpc.ServiceDesc for DiseasService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiseasService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.v1.DiseasService",
	HandlerType: (*DiseasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DiseasGet",
			Handler:    _DiseasService_DiseasGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/diseas.proto",
}
