// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/measurement_dash.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MeasurementService_MeasurementGet_FullMethodName = "/dashboard.services.v1.MeasurementService/MeasurementGet"
)

// MeasurementServiceClient is the client API for MeasurementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeasurementServiceClient interface {
	MeasurementGet(ctx context.Context, in *MeasurementGetRequest, opts ...grpc.CallOption) (*MeasurementGetReply, error)
}

type measurementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeasurementServiceClient(cc grpc.ClientConnInterface) MeasurementServiceClient {
	return &measurementServiceClient{cc}
}

func (c *measurementServiceClient) MeasurementGet(ctx context.Context, in *MeasurementGetRequest, opts ...grpc.CallOption) (*MeasurementGetReply, error) {
	out := new(MeasurementGetReply)
	err := c.cc.Invoke(ctx, MeasurementService_MeasurementGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeasurementServiceServer is the server API for MeasurementService service.
// All implementations should embed UnimplementedMeasurementServiceServer
// for forward compatibility
type MeasurementServiceServer interface {
	MeasurementGet(context.Context, *MeasurementGetRequest) (*MeasurementGetReply, error)
}

// UnimplementedMeasurementServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMeasurementServiceServer struct {
}

func (UnimplementedMeasurementServiceServer) MeasurementGet(context.Context, *MeasurementGetRequest) (*MeasurementGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MeasurementGet not implemented")
}

// UnsafeMeasurementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeasurementServiceServer will
// result in compilation errors.
type UnsafeMeasurementServiceServer interface {
	mustEmbedUnimplementedMeasurementServiceServer()
}

func RegisterMeasurementServiceServer(s grpc.ServiceRegistrar, srv MeasurementServiceServer) {
	s.RegisterService(&MeasurementService_ServiceDesc, srv)
}

func _MeasurementService_MeasurementGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasurementGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeasurementServiceServer).MeasurementGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeasurementService_MeasurementGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeasurementServiceServer).MeasurementGet(ctx, req.(*MeasurementGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeasurementService_ServiceDesc is the grpc.ServiceDesc for MeasurementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeasurementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.services.v1.MeasurementService",
	HandlerType: (*MeasurementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MeasurementGet",
			Handler:    _MeasurementService_MeasurementGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/measurement_dash.proto",
}
