// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/metric_type_dash.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MetricTypeService_MetricTypeGet_FullMethodName    = "/dashboard.services.v1.MetricTypeService/MetricTypeGet"
	MetricTypeService_MetricTypeCreate_FullMethodName = "/dashboard.services.v1.MetricTypeService/MetricTypeCreate"
)

// MetricTypeServiceClient is the client API for MetricTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricTypeServiceClient interface {
	MetricTypeGet(ctx context.Context, in *MetricTypeGetRequest, opts ...grpc.CallOption) (*MetricTypeGetReply, error)
	MetricTypeCreate(ctx context.Context, in *MetricTypeCreateRequest, opts ...grpc.CallOption) (*MetricTypeCreateReply, error)
}

type metricTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricTypeServiceClient(cc grpc.ClientConnInterface) MetricTypeServiceClient {
	return &metricTypeServiceClient{cc}
}

func (c *metricTypeServiceClient) MetricTypeGet(ctx context.Context, in *MetricTypeGetRequest, opts ...grpc.CallOption) (*MetricTypeGetReply, error) {
	out := new(MetricTypeGetReply)
	err := c.cc.Invoke(ctx, MetricTypeService_MetricTypeGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricTypeServiceClient) MetricTypeCreate(ctx context.Context, in *MetricTypeCreateRequest, opts ...grpc.CallOption) (*MetricTypeCreateReply, error) {
	out := new(MetricTypeCreateReply)
	err := c.cc.Invoke(ctx, MetricTypeService_MetricTypeCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricTypeServiceServer is the server API for MetricTypeService service.
// All implementations should embed UnimplementedMetricTypeServiceServer
// for forward compatibility
type MetricTypeServiceServer interface {
	MetricTypeGet(context.Context, *MetricTypeGetRequest) (*MetricTypeGetReply, error)
	MetricTypeCreate(context.Context, *MetricTypeCreateRequest) (*MetricTypeCreateReply, error)
}

// UnimplementedMetricTypeServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMetricTypeServiceServer struct {
}

func (UnimplementedMetricTypeServiceServer) MetricTypeGet(context.Context, *MetricTypeGetRequest) (*MetricTypeGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetricTypeGet not implemented")
}
func (UnimplementedMetricTypeServiceServer) MetricTypeCreate(context.Context, *MetricTypeCreateRequest) (*MetricTypeCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetricTypeCreate not implemented")
}

// UnsafeMetricTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricTypeServiceServer will
// result in compilation errors.
type UnsafeMetricTypeServiceServer interface {
	mustEmbedUnimplementedMetricTypeServiceServer()
}

func RegisterMetricTypeServiceServer(s grpc.ServiceRegistrar, srv MetricTypeServiceServer) {
	s.RegisterService(&MetricTypeService_ServiceDesc, srv)
}

func _MetricTypeService_MetricTypeGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricTypeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricTypeServiceServer).MetricTypeGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricTypeService_MetricTypeGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricTypeServiceServer).MetricTypeGet(ctx, req.(*MetricTypeGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricTypeService_MetricTypeCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricTypeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricTypeServiceServer).MetricTypeCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricTypeService_MetricTypeCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricTypeServiceServer).MetricTypeCreate(ctx, req.(*MetricTypeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricTypeService_ServiceDesc is the grpc.ServiceDesc for MetricTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.services.v1.MetricTypeService",
	HandlerType: (*MetricTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MetricTypeGet",
			Handler:    _MetricTypeService_MetricTypeGet_Handler,
		},
		{
			MethodName: "MetricTypeCreate",
			Handler:    _MetricTypeService_MetricTypeCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/metric_type_dash.proto",
}
