// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/patient_dash.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PatientService_PatientGet_FullMethodName      = "/dashboard.services.v1.PatientService/PatientGet"
	PatientService_PatientRetrieve_FullMethodName = "/dashboard.services.v1.PatientService/PatientRetrieve"
	PatientService_PatientCreate_FullMethodName   = "/dashboard.services.v1.PatientService/PatientCreate"
)

// PatientServiceClient is the client API for PatientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatientServiceClient interface {
	PatientGet(ctx context.Context, in *PatientGetRequest, opts ...grpc.CallOption) (*PatientGetReply, error)
	PatientRetrieve(ctx context.Context, in *PatientRetrieveRequest, opts ...grpc.CallOption) (*PatientRetrieveReply, error)
	PatientCreate(ctx context.Context, in *PatientCreateRequest, opts ...grpc.CallOption) (*PatientCreateReply, error)
}

type patientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPatientServiceClient(cc grpc.ClientConnInterface) PatientServiceClient {
	return &patientServiceClient{cc}
}

func (c *patientServiceClient) PatientGet(ctx context.Context, in *PatientGetRequest, opts ...grpc.CallOption) (*PatientGetReply, error) {
	out := new(PatientGetReply)
	err := c.cc.Invoke(ctx, PatientService_PatientGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientServiceClient) PatientRetrieve(ctx context.Context, in *PatientRetrieveRequest, opts ...grpc.CallOption) (*PatientRetrieveReply, error) {
	out := new(PatientRetrieveReply)
	err := c.cc.Invoke(ctx, PatientService_PatientRetrieve_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientServiceClient) PatientCreate(ctx context.Context, in *PatientCreateRequest, opts ...grpc.CallOption) (*PatientCreateReply, error) {
	out := new(PatientCreateReply)
	err := c.cc.Invoke(ctx, PatientService_PatientCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatientServiceServer is the server API for PatientService service.
// All implementations should embed UnimplementedPatientServiceServer
// for forward compatibility
type PatientServiceServer interface {
	PatientGet(context.Context, *PatientGetRequest) (*PatientGetReply, error)
	PatientRetrieve(context.Context, *PatientRetrieveRequest) (*PatientRetrieveReply, error)
	PatientCreate(context.Context, *PatientCreateRequest) (*PatientCreateReply, error)
}

// UnimplementedPatientServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPatientServiceServer struct {
}

func (UnimplementedPatientServiceServer) PatientGet(context.Context, *PatientGetRequest) (*PatientGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatientGet not implemented")
}
func (UnimplementedPatientServiceServer) PatientRetrieve(context.Context, *PatientRetrieveRequest) (*PatientRetrieveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatientRetrieve not implemented")
}
func (UnimplementedPatientServiceServer) PatientCreate(context.Context, *PatientCreateRequest) (*PatientCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatientCreate not implemented")
}

// UnsafePatientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatientServiceServer will
// result in compilation errors.
type UnsafePatientServiceServer interface {
	mustEmbedUnimplementedPatientServiceServer()
}

func RegisterPatientServiceServer(s grpc.ServiceRegistrar, srv PatientServiceServer) {
	s.RegisterService(&PatientService_ServiceDesc, srv)
}

func _PatientService_PatientGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServiceServer).PatientGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientService_PatientGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServiceServer).PatientGet(ctx, req.(*PatientGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientService_PatientRetrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientRetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServiceServer).PatientRetrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientService_PatientRetrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServiceServer).PatientRetrieve(ctx, req.(*PatientRetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientService_PatientCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServiceServer).PatientCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientService_PatientCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServiceServer).PatientCreate(ctx, req.(*PatientCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatientService_ServiceDesc is the grpc.ServiceDesc for PatientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.services.v1.PatientService",
	HandlerType: (*PatientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PatientGet",
			Handler:    _PatientService_PatientGet_Handler,
		},
		{
			MethodName: "PatientRetrieve",
			Handler:    _PatientService_PatientRetrieve_Handler,
		},
		{
			MethodName: "PatientCreate",
			Handler:    _PatientService_PatientCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/patient_dash.proto",
}
