// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: services/v1/patient_dash.proto

package v1

import (
	v1 "github.com/MediStatTech/dashboard-client/pb/go/models/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =====================
// PatientGet
// =====================
type PatientGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PatientGetRequest) Reset() {
	*x = PatientGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_patient_dash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientGetRequest) ProtoMessage() {}

func (x *PatientGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_patient_dash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientGetRequest.ProtoReflect.Descriptor instead.
func (*PatientGetRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_patient_dash_proto_rawDescGZIP(), []int{0}
}

type PatientGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patients []*v1.Patient_ListItem `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
}

func (x *PatientGetReply) Reset() {
	*x = PatientGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_patient_dash_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientGetReply) ProtoMessage() {}

func (x *PatientGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_patient_dash_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientGetReply.ProtoReflect.Descriptor instead.
func (*PatientGetReply) Descriptor() ([]byte, []int) {
	return file_services_v1_patient_dash_proto_rawDescGZIP(), []int{1}
}

func (x *PatientGetReply) GetPatients() []*v1.Patient_ListItem {
	if x != nil {
		return x.Patients
	}
	return nil
}

// =====================
// PatientRetrieve
// =====================
type PatientRetrieveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientId string `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
}

func (x *PatientRetrieveRequest) Reset() {
	*x = PatientRetrieveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_patient_dash_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientRetrieveRequest) ProtoMessage() {}

func (x *PatientRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_patient_dash_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientRetrieveRequest.ProtoReflect.Descriptor instead.
func (*PatientRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_patient_dash_proto_rawDescGZIP(), []int{2}
}

func (x *PatientRetrieveRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type PatientRetrieveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patient *v1.Patient_Read `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
}

func (x *PatientRetrieveReply) Reset() {
	*x = PatientRetrieveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_patient_dash_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientRetrieveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientRetrieveReply) ProtoMessage() {}

func (x *PatientRetrieveReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_patient_dash_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientRetrieveReply.ProtoReflect.Descriptor instead.
func (*PatientRetrieveReply) Descriptor() ([]byte, []int) {
	return file_services_v1_patient_dash_proto_rawDescGZIP(), []int{3}
}

func (x *PatientRetrieveReply) GetPatient() *v1.Patient_Read {
	if x != nil {
		return x.Patient
	}
	return nil
}

// =====================
// PatientCreate
// =====================
type PatientCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patient *v1.Patient_Create `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
}

func (x *PatientCreateRequest) Reset() {
	*x = PatientCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_patient_dash_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientCreateRequest) ProtoMessage() {}

func (x *PatientCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_patient_dash_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientCreateRequest.ProtoReflect.Descriptor instead.
func (*PatientCreateRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_patient_dash_proto_rawDescGZIP(), []int{4}
}

func (x *PatientCreateRequest) GetPatient() *v1.Patient_Create {
	if x != nil {
		return x.Patient
	}
	return nil
}

type PatientCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patient *v1.Patient_Read `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
}

func (x *PatientCreateReply) Reset() {
	*x = PatientCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_patient_dash_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientCreateReply) ProtoMessage() {}

func (x *PatientCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_patient_dash_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientCreateReply.ProtoReflect.Descriptor instead.
func (*PatientCreateReply) Descriptor() ([]byte, []int) {
	return file_services_v1_patient_dash_proto_rawDescGZIP(), []int{5}
}

func (x *PatientCreateReply) GetPatient() *v1.Patient_Read {
	if x != nil {
		return x.Patient
	}
	return nil
}

var File_services_v1_patient_dash_proto protoreflect.FileDescriptor

var file_services_v1_patient_dash_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x15, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x73, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x0f, 0x50, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x41, 0x0a,
	0x08, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x37, 0x0a, 0x16, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x14, 0x50, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3b, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x55,
	0x0a, 0x14, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x07, 0x70, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x12, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x07, 0x70,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64,
	0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x07, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x32, 0xc8, 0x02, 0x0a, 0x0e, 0x50, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x0a, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x12, 0x28, 0x2e, 0x64, 0x61, 0x73, 0x68,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6d, 0x0a, 0x0f, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x12, 0x2d,
	0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e,
	0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x67, 0x0a, 0x0d, 0x50, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x2e, 0x64, 0x61,
	0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4d, 0x65, 0x64, 0x69, 0x53, 0x74, 0x61, 0x74, 0x54, 0x65, 0x63, 0x68, 0x2f, 0x64,
	0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f,
	0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_v1_patient_dash_proto_rawDescOnce sync.Once
	file_services_v1_patient_dash_proto_rawDescData = file_services_v1_patient_dash_proto_rawDesc
)

func file_services_v1_patient_dash_proto_rawDescGZIP() []byte {
	file_services_v1_patient_dash_proto_rawDescOnce.Do(func() {
		file_services_v1_patient_dash_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_v1_patient_dash_proto_rawDescData)
	})
	return file_services_v1_patient_dash_proto_rawDescData
}

var file_services_v1_patient_dash_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_v1_patient_dash_proto_goTypes = []interface{}{
	(*PatientGetRequest)(nil),      // 0: dashboard.services.v1.PatientGetRequest
	(*PatientGetReply)(nil),        // 1: dashboard.services.v1.PatientGetReply
	(*PatientRetrieveRequest)(nil), // 2: dashboard.services.v1.PatientRetrieveRequest
	(*PatientRetrieveReply)(nil),   // 3: dashboard.services.v1.PatientRetrieveReply
	(*PatientCreateRequest)(nil),   // 4: dashboard.services.v1.PatientCreateRequest
	(*PatientCreateReply)(nil),     // 5: dashboard.services.v1.PatientCreateReply
	(*v1.Patient_ListItem)(nil),    // 6: dashboard.models.v1.Patient.ListItem
	(*v1.Patient_Read)(nil),        // 7: dashboard.models.v1.Patient.Read
	(*v1.Patient_Create)(nil),      // 8: dashboard.models.v1.Patient.Create
}
var file_services_v1_patient_dash_proto_depIdxs = []int32{
	6, // 0: dashboard.services.v1.PatientGetReply.patients:type_name -> dashboard.models.v1.Patient.ListItem
	7, // 1: dashboard.services.v1.PatientRetrieveReply.patient:type_name -> dashboard.models.v1.Patient.Read
	8, // 2: dashboard.services.v1.PatientCreateRequest.patient:type_name -> dashboard.models.v1.Patient.Create
	7, // 3: dashboard.services.v1.PatientCreateReply.patient:type_name -> dashboard.models.v1.Patient.Read
	0, // 4: dashboard.services.v1.PatientService.PatientGet:input_type -> dashboard.services.v1.PatientGetRequest
	2, // 5: dashboard.services.v1.PatientService.PatientRetrieve:input_type -> dashboard.services.v1.PatientRetrieveRequest
	4, // 6: dashboard.services.v1.PatientService.PatientCreate:input_type -> dashboard.services.v1.PatientCreateRequest
	1, // 7: dashboard.services.v1.PatientService.PatientGet:output_type -> dashboard.services.v1.PatientGetReply
	3, // 8: dashboard.services.v1.PatientService.PatientRetrieve:output_type -> dashboard.services.v1.PatientRetrieveReply
	5, // 9: dashboard.services.v1.PatientService.PatientCreate:output_type -> dashboard.services.v1.PatientCreateReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_v1_patient_dash_proto_init() }
func file_services_v1_patient_dash_proto_init() {
	if File_services_v1_patient_dash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_v1_patient_dash_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_patient_dash_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_patient_dash_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientRetrieveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_patient_dash_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientRetrieveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_patient_dash_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_patient_dash_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_v1_patient_dash_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_patient_dash_proto_goTypes,
		DependencyIndexes: file_services_v1_patient_dash_proto_depIdxs,
		MessageInfos:      file_services_v1_patient_dash_proto_msgTypes,
	}.Build()
	File_services_v1_patient_dash_proto = out.File
	file_services_v1_patient_dash_proto_rawDesc = nil
	file_services_v1_patient_dash_proto_goTypes = nil
	file_services_v1_patient_dash_proto_depIdxs = nil
}
