// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/sensor_dash.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SensorService_SensorGet_FullMethodName    = "/dashboard.services.v1.SensorService/SensorGet"
	SensorService_SensorCreate_FullMethodName = "/dashboard.services.v1.SensorService/SensorCreate"
)

// SensorServiceClient is the client API for SensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorServiceClient interface {
	SensorGet(ctx context.Context, in *SensorGetRequest, opts ...grpc.CallOption) (*SensorGetReply, error)
	SensorCreate(ctx context.Context, in *SensorCreateRequest, opts ...grpc.CallOption) (*SensorCreateReply, error)
}

type sensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorServiceClient(cc grpc.ClientConnInterface) SensorServiceClient {
	return &sensorServiceClient{cc}
}

func (c *sensorServiceClient) SensorGet(ctx context.Context, in *SensorGetRequest, opts ...grpc.CallOption) (*SensorGetReply, error) {
	out := new(SensorGetReply)
	err := c.cc.Invoke(ctx, SensorService_SensorGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) SensorCreate(ctx context.Context, in *SensorCreateRequest, opts ...grpc.CallOption) (*SensorCreateReply, error) {
	out := new(SensorCreateReply)
	err := c.cc.Invoke(ctx, SensorService_SensorCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorServiceServer is the server API for SensorService service.
// All implementations should embed UnimplementedSensorServiceServer
// for forward compatibility
type SensorServiceServer interface {
	SensorGet(context.Context, *SensorGetRequest) (*SensorGetReply, error)
	SensorCreate(context.Context, *SensorCreateRequest) (*SensorCreateReply, error)
}

// UnimplementedSensorServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSensorServiceServer struct {
}

func (UnimplementedSensorServiceServer) SensorGet(context.Context, *SensorGetRequest) (*SensorGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SensorGet not implemented")
}
func (UnimplementedSensorServiceServer) SensorCreate(context.Context, *SensorCreateRequest) (*SensorCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SensorCreate not implemented")
}

// UnsafeSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServiceServer will
// result in compilation errors.
type UnsafeSensorServiceServer interface {
	mustEmbedUnimplementedSensorServiceServer()
}

func RegisterSensorServiceServer(s grpc.ServiceRegistrar, srv SensorServiceServer) {
	s.RegisterService(&SensorService_ServiceDesc, srv)
}

func _SensorService_SensorGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).SensorGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_SensorGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).SensorGet(ctx, req.(*SensorGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_SensorCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).SensorCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_SensorCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).SensorCreate(ctx, req.(*SensorCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorService_ServiceDesc is the grpc.ServiceDesc for SensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.services.v1.SensorService",
	HandlerType: (*SensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SensorGet",
			Handler:    _SensorService_SensorGet_Handler,
		},
		{
			MethodName: "SensorCreate",
			Handler:    _SensorService_SensorCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/sensor_dash.proto",
}
