// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: services/v1/staff_dash.proto

package v1

import (
	v1 "github.com/MediStatTech/dashboard-client/pb/go/models/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =====================
// StaffRetrieve
// =====================
type StaffRetrieveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StaffRetrieveRequest) Reset() {
	*x = StaffRetrieveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staff_dash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffRetrieveRequest) ProtoMessage() {}

func (x *StaffRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staff_dash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffRetrieveRequest.ProtoReflect.Descriptor instead.
func (*StaffRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_staff_dash_proto_rawDescGZIP(), []int{0}
}

type StaffRetrieveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staff *v1.Staff_Read `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
}

func (x *StaffRetrieveReply) Reset() {
	*x = StaffRetrieveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staff_dash_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffRetrieveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffRetrieveReply) ProtoMessage() {}

func (x *StaffRetrieveReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staff_dash_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffRetrieveReply.ProtoReflect.Descriptor instead.
func (*StaffRetrieveReply) Descriptor() ([]byte, []int) {
	return file_services_v1_staff_dash_proto_rawDescGZIP(), []int{1}
}

func (x *StaffRetrieveReply) GetStaff() *v1.Staff_Read {
	if x != nil {
		return x.Staff
	}
	return nil
}

var File_services_v1_staff_dash_proto protoreflect.FileDescriptor

var file_services_v1_staff_dash_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x5f, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15,
	0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x12, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x35, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x32, 0x77, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x66, 0x66, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x12, 0x2b, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x65,
	0x64, 0x69, 0x53, 0x74, 0x61, 0x74, 0x54, 0x65, 0x63, 0x68, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x67,
	0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_v1_staff_dash_proto_rawDescOnce sync.Once
	file_services_v1_staff_dash_proto_rawDescData = file_services_v1_staff_dash_proto_rawDesc
)

func file_services_v1_staff_dash_proto_rawDescGZIP() []byte {
	file_services_v1_staff_dash_proto_rawDescOnce.Do(func() {
		file_services_v1_staff_dash_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_v1_staff_dash_proto_rawDescData)
	})
	return file_services_v1_staff_dash_proto_rawDescData
}

var file_services_v1_staff_dash_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_v1_staff_dash_proto_goTypes = []interface{}{
	(*StaffRetrieveRequest)(nil), // 0: dashboard.services.v1.StaffRetrieveRequest
	(*StaffRetrieveReply)(nil),   // 1: dashboard.services.v1.StaffRetrieveReply
	(*v1.Staff_Read)(nil),        // 2: dashboard.models.v1.Staff.Read
}
var file_services_v1_staff_dash_proto_depIdxs = []int32{
	2, // 0: dashboard.services.v1.StaffRetrieveReply.staff:type_name -> dashboard.models.v1.Staff.Read
	0, // 1: dashboard.services.v1.StaffService.StaffRetrieve:input_type -> dashboard.services.v1.StaffRetrieveRequest
	1, // 2: dashboard.services.v1.StaffService.StaffRetrieve:output_type -> dashboard.services.v1.StaffRetrieveReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_v1_staff_dash_proto_init() }
func file_services_v1_staff_dash_proto_init() {
	if File_services_v1_staff_dash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_v1_staff_dash_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffRetrieveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_staff_dash_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffRetrieveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_v1_staff_dash_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_staff_dash_proto_goTypes,
		DependencyIndexes: file_services_v1_staff_dash_proto_depIdxs,
		MessageInfos:      file_services_v1_staff_dash_proto_msgTypes,
	}.Build()
	File_services_v1_staff_dash_proto = out.File
	file_services_v1_staff_dash_proto_rawDesc = nil
	file_services_v1_staff_dash_proto_goTypes = nil
	file_services_v1_staff_dash_proto_depIdxs = nil
}
