// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: models/v1/metric_type_dash.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetricTypeId string  `protobuf:"bytes,1,opt,name=metric_type_id,json=metricTypeId,proto3" json:"metric_type_id,omitempty"`
	SensorId     string  `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Code         string  `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name         string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Symbol       string  `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MinValue     float64 `protobuf:"fixed64,6,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue     float64 `protobuf:"fixed64,7,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
}

func (x *MetricType) Reset() {
	*x = MetricType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_metric_type_dash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricType) ProtoMessage() {}

func (x *MetricType) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_metric_type_dash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricType.ProtoReflect.Descriptor instead.
func (*MetricType) Descriptor() ([]byte, []int) {
	return file_models_v1_metric_type_dash_proto_rawDescGZIP(), []int{0}
}

func (x *MetricType) GetMetricTypeId() string {
	if x != nil {
		return x.MetricTypeId
	}
	return ""
}

func (x *MetricType) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *MetricType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MetricType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricType) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MetricType) GetMinValue() float64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *MetricType) GetMaxValue() float64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

var File_models_v1_metric_type_dash_proto protoreflect.FileDescriptor

var file_models_v1_metric_type_dash_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x13, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xc9, 0x01, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6d, 0x69,
	0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4d, 0x65, 0x64, 0x69, 0x53, 0x74, 0x61, 0x74, 0x54, 0x65, 0x63, 0x68, 0x2f, 0x64,
	0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f,
	0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_v1_metric_type_dash_proto_rawDescOnce sync.Once
	file_models_v1_metric_type_dash_proto_rawDescData = file_models_v1_metric_type_dash_proto_rawDesc
)

func file_models_v1_metric_type_dash_proto_rawDescGZIP() []byte {
	file_models_v1_metric_type_dash_proto_rawDescOnce.Do(func() {
		file_models_v1_metric_type_dash_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_v1_metric_type_dash_proto_rawDescData)
	})
	return file_models_v1_metric_type_dash_proto_rawDescData
}

var file_models_v1_metric_type_dash_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_v1_metric_type_dash_proto_goTypes = []interface{}{
	(*MetricType)(nil), // 0: dashboard.models.v1.MetricType
}
var file_models_v1_metric_type_dash_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_v1_metric_type_dash_proto_init() }
func file_models_v1_metric_type_dash_proto_init() {
	if File_models_v1_metric_type_dash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_v1_metric_type_dash_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_v1_metric_type_dash_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_v1_metric_type_dash_proto_goTypes,
		DependencyIndexes: file_models_v1_metric_type_dash_proto_depIdxs,
		MessageInfos:      file_models_v1_metric_type_dash_proto_msgTypes,
	}.Build()
	File_models_v1_metric_type_dash_proto = out.File
	file_models_v1_metric_type_dash_proto_rawDesc = nil
	file_models_v1_metric_type_dash_proto_goTypes = nil
	file_models_v1_metric_type_dash_proto_depIdxs = nil
}
